### ISSUE TITLE
Possible typo bug

### ISSUE THREAD

**Issue by akmohtashami** [epfl-lara/treenet#2]
Hi,

I think the following line has a typo and `child` should actually be `other_child`.

https://github.com/epfl-lara/treenet/blob/ca90c60dfb07149e3fad58b07078b8489aab5100/treenet/treelstm.py#L81

Also, I think `f_base` should be cloned in the following line rather than just simple assignment:

https://github.com/epfl-lara/treenet/blob/ca90c60dfb07149e3fad58b07078b8489aab5100/treenet/treelstm.py#L79

If confirmed, I can send a PR to fix these issues.

**Comment by redelmann** [comment]
Hi,

Sorry for the delay. Indeed, you are correct.
Thanks a lot for the bug report. The issue has been fixed in ` [a7dd196](/epfl-lara/treenet/commit/a7dd196219a20ae43f9588ed83005c5c4df8db5d)`.
